# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/ulefone/bretzel/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/ulefone/

PRODUCT_COPY_FILES += \
    vendor/ulefone/bretzel/proprietary/bin/netd:system/bin/netd \
    vendor/ulefone/bretzel/proprietary/bin/kpoc_charger:system/bin/kpoc_charger \
    vendor/ulefone/bretzel/proprietary/etc/init/kpoc_charger.rc:system/etc/init/kpoc_charger.rc \
    vendor/ulefone/bretzel/proprietary/lib/libshowlogo.so:system/lib/libshowlogo.so \
    vendor/ulefone/bretzel/proprietary/lib/libsysenv_system.so:system/lib/libsysenv_system.so \
    vendor/ulefone/bretzel/proprietary/lib64/libmtk-ril.so:system/lib64/libmtk-ril.so \
    vendor/ulefone/bretzel/proprietary/bin/nfcstackp:system/bin/nfcstackp \
    vendor/ulefone/bretzel/proprietary/etc/nfcee_access.xml:system/etc/nfcee_access.xml \
    vendor/ulefone/bretzel/proprietary/etc/permissions/com.st.android.nfc_dta_extensions.xml:system/etc/permissions/com.st.android.nfc_dta_extensions.xml \
    vendor/ulefone/bretzel/proprietary/etc/permissions/com.st.android.nfc_extensions.xml:system/etc/permissions/com.st.android.nfc_extensions.xml \
    vendor/ulefone/bretzel/proprietary/lib/libdtaNfaProvider.so:system/lib/libdtaNfaProvider.so \
    vendor/ulefone/bretzel/proprietary/lib/libhui.so:system/lib/libhui.so \
    vendor/ulefone/bretzel/proprietary/lib/libicuXD.so:system/lib/libicuXD.so \
    vendor/ulefone/bretzel/proprietary/lib/libnfc_st_dta.so:system/lib/libnfc_st_dta.so \
    vendor/ulefone/bretzel/proprietary/lib/libnfc_st_dta_jni.so:system/lib/libnfc_st_dta_jni.so \
    vendor/ulefone/bretzel/proprietary/lib/libstnfc-nci.so:system/lib/libstnfc-nci.so \
    vendor/ulefone/bretzel/proprietary/lib/libstnfc_nci_jni.so:system/lib/libstnfc_nci_jni.so \
    vendor/ulefone/bretzel/proprietary/lib64/libdtaNfaProvider.so:system/lib64/libdtaNfaProvider.so \
    vendor/ulefone/bretzel/proprietary/lib64/libhui.so:system/lib64/libhui.so \
    vendor/ulefone/bretzel/proprietary/lib64/libicuXD.so:system/lib64/libicuXD.so \
    vendor/ulefone/bretzel/proprietary/lib64/libnfc_st_dta.so:system/lib64/libnfc_st_dta.so \
    vendor/ulefone/bretzel/proprietary/lib64/libnfc_st_dta_jni.so:system/lib64/libnfc_st_dta_jni.so \
    vendor/ulefone/bretzel/proprietary/lib64/libstnfc-nci.so:system/lib64/libstnfc-nci.so \
    vendor/ulefone/bretzel/proprietary/lib64/libstnfc_nci_jni.so:system/lib64/libstnfc_nci_jni.so
    	
PRODUCT_PACKAGES += \
    CameraGo \
    Nfc_st \
    com.st.android.nfc_dta_extensions \
    com.st.android.nfc_extensions
